// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gibbsC
NumericMatrix gibbsC(double a, double b, int n, int N);
RcppExport SEXP _SA23204175_gibbsC(SEXP aSEXP, SEXP bSEXP, SEXP nSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbsC(a, b, n, N));
    return rcpp_result_gen;
END_RCPP
}
// compute_ratio_cpp
double compute_ratio_cpp(NumericMatrix x, NumericVector y, NumericVector beta_star, double sigma_hat);
RcppExport SEXP _SA23204175_compute_ratio_cpp(SEXP xSEXP, SEXP ySEXP, SEXP beta_starSEXP, SEXP sigma_hatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_star(beta_starSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_hat(sigma_hatSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_ratio_cpp(x, y, beta_star, sigma_hat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SA23204175_gibbsC", (DL_FUNC) &_SA23204175_gibbsC, 4},
    {"_SA23204175_compute_ratio_cpp", (DL_FUNC) &_SA23204175_compute_ratio_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SA23204175(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
