# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbsC <- function(a, b, n, N) {
    .Call('_SA23204175_gibbsC', PACKAGE = 'SA23204175', a, b, n, N)
}

#' @title Compute sigma.hat/sigma.star for evaluation
#' @description More details refer to scaled sparse linear regression
#' @param x the design matrix
#' @param y the response vector
#' @param beta_star the true coefficient vector of beta
#' @param sigma_hat the estimator of sigma
#' @return sigma_hat/sigma_star
#' @examples 
#' \dontrun{
#'    compute_ratio_cpp(d1[,1:1000],as.vector(d1[,1001]),rep(0,1000),1)
#' }
#' @export
compute_ratio_cpp <- function(x, y, beta_star, sigma_hat) {
    .Call('_SA23204175_compute_ratio_cpp', PACKAGE = 'SA23204175', x, y, beta_star, sigma_hat)
}

